"""Interactive setup wizard — from a fresh fork to a working instance.

Walks: X app credentials -> OAuth browser flow -> bookmark-folder -> topic mapping ->
account mirrors -> GitHub Actions secrets. Every effectful edge is injected via
WizardDeps, so the complete flow is unit-testable offline; bin/init_wizard.py provides
the real implementations (terminal I/O, subprocess OAuth, gh CLI).

Re-runnable by design: existing config files are shown and require explicit consent
before being replaced; credentials already present in the env file are kept as defaults.
"""
from __future__ import annotations

import os
from collections.abc import Callable
from dataclasses import dataclass, field

from .model_config import (
    ModelConfig,
    detect_setup_provider,
    model_config_toml,
    provider_for,
)
from .secrets_push import LIVE_INSTANCE_SECRET_NAMES, LIVE_INSTANCE_VARIABLE

X_APP_URL = "https://developer.x.com/en/portal/dashboard"
PAT_URL = "https://github.com/settings/personal-access-tokens/new"

# Base secrets the GitHub Actions workflows need before adding the selected model provider.
BASE_SECRET_NAMES = ("X_CLIENT_ID", "X_CLIENT_SECRET", "X_BEARER_TOKEN", "X_TOKENS",
                     "GH_PAT")

EXAMPLE_ACCOUNTS = (
    {"handle": "thsottiaux", "topic": "openai", "label": "Thibault (OpenAI)"},
    {"handle": "bcherny", "topic": "claude-code", "label": "Boris (Anthropic)"},
    {"handle": "OfficialLoganK", "topic": "google-ai", "label": "Logan (Google)"},
    {"handle": "santiagomed", "topic": "xai", "label": "Santiago (xAI)"},
)


@dataclass
class WizardIO:
    """Terminal seam: ask/say/confirm. Tests script `answers`; bin wires input()/print()."""
    ask: Callable[[str], str]
    say: Callable[[str], None]

    def confirm(self, prompt: str, *, default: bool = True) -> bool:
        suffix = " [Y/n] " if default else " [y/N] "
        raw = self.ask(prompt + suffix).strip().lower()
        if not raw:
            return default
        return raw in ("y", "yes")


@dataclass
class WizardDeps:
    """Effectful collaborators, all injectable.

    oauth_flow():            run the browser OAuth dance; returns True on success.
    load_tokens():           return the saved token JSON string ('' if missing).
    make_folder_client():    client with .folders() using the saved tokens.
    gh_available():          is the GitHub CLI installed and authenticated?
    set_secret(name, value): push one Actions secret; returns True on success.
    set_variable(name, value): set repo variables such as live-instance enablement.
    read_env()/write_env():  the gitignored credentials file (KEY=VALUE dict).
    read_config(name)/write_config(name, text): config/<name> contents.
    """
    oauth_flow: Callable[[], bool]
    load_tokens: Callable[[], str]
    make_folder_client: Callable[[], object]
    gh_available: Callable[[], bool]
    set_secret: Callable[[str, str], bool]
    read_env: Callable[[], dict]
    write_env: Callable[[dict], None]
    read_config: Callable[[str], str]
    write_config: Callable[[str, str], None]
    set_variable: Callable[[str, str], bool] = lambda _name, _value: False


@dataclass
class WizardResult:
    topics: dict[str, list[str]] = field(default_factory=dict)
    accounts: list[dict] = field(default_factory=list)
    recaps: list[dict] = field(default_factory=list)
    secrets_set: list[str] = field(default_factory=list)
    variables_set: list[str] = field(default_factory=list)
    remaining: list[str] = field(default_factory=list)
    aborted: bool = False


def topics_toml(topics: dict[str, list[str]]) -> str:
    lines = ["# Bookmark folders -> wiki topics. Generated by `bowerbird init`.", ""]
    for name, folder_ids in topics.items():
        ids = ", ".join(f'"{i}"' for i in folder_ids)
        lines += [f"[topics.{name}]", f"folder_ids = [{ids}]", ""]
    return "\n".join(lines)


def accounts_toml(accounts: list[dict]) -> str:
    lines = ["# X accounts to mirror. Generated by `bowerbird init`.", ""]
    for a in accounts:
        lines += [
            "[[handles]]",
            f'handle = "{a["handle"]}"',
            f'topic = "{a["topic"]}"',
        ]
        if a.get("label"):
            lines.append(f'label = "{a["label"]}"')
        lines += ['off_topic = "skip"', ""]
    return "\n".join(lines)


def recaps_toml(profiles: list[dict]) -> str:
    lines = [
        "# Active recap profiles. Presence means enabled.",
        "# Generated by `bowerbird init`; edit destinations after Slack/email setup.",
        "",
    ]
    for profile in profiles:
        topics = ", ".join(f'"{topic}"' for topic in profile.get("topics", []))
        accounts = ", ".join(f'"{account}"' for account in profile.get("accounts", []))
        lines += [
            "[[recaps]]",
            f'name = "{profile["name"]}"',
            f'frequency = "{profile["frequency"]}"',
        ]
        if profile["frequency"] == "weekly":
            lines.append('weekly_due_day = "monday"')
        if topics:
            lines.append(f"topics = [{topics}]")
        if accounts:
            lines.append(f"accounts = [{accounts}]")
        lines += [
            'prompt = "compile/recaps/default.md"',
            'format = "markdown"',
            "",
        ]
    return "\n".join(lines)


def _slug(name: str) -> str:
    cleaned = "".join(c if (c.isalnum() or c in "-_") else "-" for c in name.strip().lower())
    return cleaned.strip("-") or "topic"


def _collect_credentials(io: WizardIO, deps: WizardDeps) -> dict:
    env = deps.read_env()
    io.say("Step 1/6 — X app credentials")
    io.say(f"You need an X developer app with pay-as-you-go billing: {X_APP_URL}")
    io.say("Required: OAuth 2.0 client id/secret (user auth, redirect "
           "http://bowerbird.localhost:8080/callback) and an app-only bearer token.")
    for key, label in (("X_CLIENT_ID", "OAuth2 client id"),
                       ("X_CLIENT_SECRET", "OAuth2 client secret (empty for public client)"),
                       ("X_BEARER_TOKEN", "app-only bearer token")):
        current = env.get(key, "")
        prompt = f"{label}" + (f" [keep saved value]" if current else "") + ": "
        value = io.ask(prompt).strip()
        if value:
            env[key] = value
        elif not current and key != "X_CLIENT_SECRET":
            io.say(f"  ({key} left empty — the pipeline will not run without it)")
    env.setdefault("X_REDIRECT_URI", "http://bowerbird.localhost:8080/callback")
    env.setdefault("X_SCOPES", "bookmark.read tweet.read users.read offline.access")
    deps.write_env(env)
    return env


def _run_oauth(io: WizardIO, deps: WizardDeps) -> bool:
    io.say("Step 2/6 — authorize with X (a browser window will open)")
    if deps.load_tokens() and not io.confirm("Tokens already saved. Re-run the OAuth flow?",
                                             default=False):
        return True
    ok = deps.oauth_flow()
    io.say("authorized." if ok else "OAuth flow failed — finish setup later with `bowerbird auth`.")
    return ok


def _map_folders(io: WizardIO, deps: WizardDeps, authed: bool) -> dict[str, list[str]]:
    io.say("Step 3/6 — choose which bookmark folders Bowerbird watches")
    io.say("Watching a folder means anything you bookmark into it becomes part of "
           "your knowledge base. Most people start with one or two folders — you "
           "can add more any time.")
    existing = deps.read_config("topics.toml")
    if existing.strip():
        io.say("Current config/topics.toml:\n" + existing)
        if not io.confirm("Replace it with a new mapping?", default=False):
            return {}
    folders: list[dict] = []
    if authed:
        try:
            folders = deps.make_folder_client().folders()
        except Exception as e:  # noqa: BLE001 — keep the wizard going; folders are retryable
            io.say(f"could not list folders ({e}); enter ids manually.")
    topics: dict[str, list[str]] = {}
    if folders:
        for f in folders:
            answer = io.ask(
                f"Watch '{f.get('name', '?')}'? Wiki section name to file it under "
                f"(Enter to skip): "
            ).strip()
            if answer:
                topics.setdefault(_slug(answer), []).append(f["id"])
    else:
        while True:
            fid = io.ask("Bookmark folder id (empty to finish): ").strip()
            if not fid:
                break
            topic = io.ask(f"Topic for folder {fid}: ").strip()
            if topic:
                topics.setdefault(_slug(topic), []).append(fid)
    if topics:
        deps.write_config("topics.toml", topics_toml(topics))
        io.say(f"wrote config/topics.toml ({len(topics)} topic(s)).")
    else:
        io.say("no folders watched — bookmark ingestion stays off until you add some.")
    return topics


def _collect_accounts(io: WizardIO, deps: WizardDeps) -> list[dict]:
    io.say("Step 4/6 — follow whole X accounts (optional)")
    io.say("Following an account mirrors every post + reply they make into your "
           "knowledge base. Each followed post is a paid API read.")
    io.say("If you do not know what to mirror yet, Bowerbird can offer four public "
           "AI accounts as examples during setup. They are not baked into the source "
           "repo; choosing them here writes them into your fork's config.")
    existing = deps.read_config("accounts.toml")
    if existing.strip():
        io.say("Current config/accounts.toml:\n" + existing)
        if not io.confirm("Replace it with a new list?", default=False):
            return []
    accounts: list[dict] = []
    if io.confirm("Use the four example AI accounts for a first account recap?", default=False):
        accounts.extend(dict(account) for account in EXAMPLE_ACCOUNTS)
        io.say("added example accounts: " + ", ".join(f"@{a['handle']}" for a in EXAMPLE_ACCOUNTS))
    while True:
        handle = io.ask("Account handle to mirror (without @, empty to finish): ").strip().lstrip("@")
        if not handle:
            break
        topic = io.ask(f"Wiki topic for @{handle}'s notes: ").strip()
        accounts.append({"handle": handle, "topic": _slug(topic or handle)})
    if accounts:
        deps.write_config("accounts.toml", accounts_toml(accounts))
        io.say(f"wrote config/accounts.toml ({len(accounts)} account(s)).")
    return accounts


def _recap_frequency(answer: str) -> str:
    value = answer.strip().lower()
    if value in ("", "d", "daily"):
        return "daily"
    if value in ("w", "weekly"):
        return "weekly"
    return "daily"


def _configure_recaps(io: WizardIO, deps: WizardDeps, topics: dict[str, list[str]],
                      accounts: list[dict]) -> list[dict]:
    io.say("Step 5/6 — recap profiles")
    existing = deps.read_config("recaps.toml")
    if existing.strip():
        io.say("Current config/recaps.toml:\n" + existing)
        if not io.confirm("Replace it with new recap profiles?", default=False):
            return []
    profiles: list[dict] = []
    for topic in topics:
        if not io.confirm(f"Create a recap profile for topic '{topic}'?", default=True):
            continue
        frequency = _recap_frequency(io.ask(f"Frequency for '{topic}' recap: daily or weekly [daily]: "))
        profiles.append({
            "name": f"{topic}-{frequency}",
            "frequency": frequency,
            "topics": [topic],
        })
    if accounts and io.confirm("Create a daily account recap profile for followed accounts?",
                               default=True):
        profiles.append({
            "name": "accounts-daily",
            "frequency": "daily",
            "accounts": [account["handle"] for account in accounts],
        })
    if profiles:
        deps.write_config("recaps.toml", recaps_toml(profiles))
        io.say(f"wrote config/recaps.toml ({len(profiles)} profile(s)).")
    else:
        io.say("no recap profiles added — add one later in config/recaps.toml.")
    return profiles


def _ask_secret(io: WizardIO, env: dict, key: str) -> str:
    """Prompt for a secret, honoring a value staged in the env file (e.g. by an
    agent piping a Copy-button credential straight into bin/.env). Enter keeps
    the staged value; typing replaces it."""
    if env.get(key):
        value = io.ask(f"{key} [saved value found — Enter to keep]: ").strip()
    else:
        value = io.ask(f"{key} (empty to set up later): ").strip()
    if value:
        env[key] = value
    return env.get(key, "")


def _select_model_provider(io: WizardIO, deps: WizardDeps, env: dict) -> ModelConfig:
    existing = deps.read_config("models.toml")
    current = ModelConfig(provider=detect_setup_provider())
    if existing.strip():
        try:
            from .model_config import parse_model_config

            current = parse_model_config(existing)
        except Exception as e:  # noqa: BLE001 - a bad config can be replaced here
            io.say(f"could not parse config/models.toml ({e}); choosing a new provider.")

    default_provider = provider_for(env.get("BOWERBIRD_MODEL_PROVIDER") or current.provider)
    io.say("Model provider for compile and recap automation")
    io.say("Pick the hosted API provider Bowerbird should use in GitHub Actions and "
           "recap delivery. Your local agent helps set this up, but CI still needs "
           "an API key.")
    for p in ("openai", "anthropic", "gemini"):
        provider = provider_for(p)
        io.say(f"  - {provider.key}: {provider.label} ({provider.api_key_name})")
    answer = io.ask(f"Provider [{default_provider.key}]: ").strip()
    provider = provider_for(answer or default_provider.key)
    model = io.ask("Model id (Enter for provider default): ").strip()
    config = ModelConfig(provider=provider.key, model=model)
    deps.write_config("models.toml", model_config_toml(config))
    env["COMPILE_RUNNER"] = provider.compile_runner
    env["RECAP_PROVIDER"] = provider.key
    if config.recap_model_effective:
        env["RECAP_MODEL"] = config.recap_model_effective
    return config


def _push_secrets(io: WizardIO, deps: WizardDeps, env: dict, result: WizardResult) -> None:
    io.say("Step 6/6 — GitHub Actions secrets")
    model_config = _select_model_provider(io, deps, env)
    provider = provider_for(model_config.provider)
    values = {
        "X_CLIENT_ID": env.get("X_CLIENT_ID", ""),
        "X_CLIENT_SECRET": env.get("X_CLIENT_SECRET", ""),
        "X_BEARER_TOKEN": env.get("X_BEARER_TOKEN", ""),
        "X_TOKENS": deps.load_tokens(),
    }
    io.say(f"GH_PAT: fine-grained PAT that can write this repo's secrets ({PAT_URL})")
    values["GH_PAT"] = _ask_secret(io, env, "GH_PAT")
    io.say(f"{provider.api_key_name}: create an API key for {provider.label} at "
           f"{provider.api_key_url}.")
    values[provider.api_key_name] = _ask_secret(io, env, provider.api_key_name)
    deps.write_env(env)  # persist anything newly typed so re-runs keep it

    secret_names = (*BASE_SECRET_NAMES, provider.api_key_name)
    missing = [n for n in secret_names if not values.get(n)]
    present = {n: v for n, v in values.items() if v}
    if deps.gh_available():
        for name, value in present.items():
            if deps.set_secret(name, value):
                result.secrets_set.append(name)
                io.say(f"  set {name}")
            else:
                result.remaining.append(f"set the {name} repo secret (gh failed)")
    else:
        io.say("GitHub CLI not available — set these repo secrets manually "
               "(Settings -> Secrets and variables -> Actions):")
        io.say("  config/models.toml records the selected model provider; commit it.")
        for name in present:
            io.say(f"  secret {name}")
            result.remaining.append(f"set the {name} repo secret")
    for name in missing:
        result.remaining.append(f"obtain and set the {name} secret")
    if all(values.get(name) for name in LIVE_INSTANCE_SECRET_NAMES):
        if deps.set_variable(LIVE_INSTANCE_VARIABLE, "true"):
            result.variables_set.append(LIVE_INSTANCE_VARIABLE)
            io.say(f"  set {LIVE_INSTANCE_VARIABLE}")
        else:
            result.remaining.append(f"set the {LIVE_INSTANCE_VARIABLE} repo variable to true")


def run_wizard(io: WizardIO, deps: WizardDeps) -> WizardResult:
    result = WizardResult()
    io.say("bowerbird init — set up your knowledge-base instance.")
    env = _collect_credentials(io, deps)
    authed = _run_oauth(io, deps)
    if not authed:
        result.remaining.append("run `bowerbird auth` to finish X authorization")
    result.topics = _map_folders(io, deps, authed)
    result.accounts = _collect_accounts(io, deps)
    result.recaps = _configure_recaps(io, deps, result.topics, result.accounts)
    _push_secrets(io, deps, env, result)

    io.say("Done. Next steps:")
    steps = [
        "commit config/ changes and push",
        "enable GitHub Actions on your fork (Actions tab)",
        "run pull-bookmarks once with limit_per_folder=3, then run account-dump",
        "confirm compile-wiki goes green and `bowerbird lint` passes",
    ]
    for item in result.remaining:
        io.say(f"  ! {item}")
    for s in steps:
        io.say(f"  - {s}")
    return result
